### ISSUE TITLE
Unable to deserialize avro?

### ISSUE THREAD

**Issue by dajoni** [Landoop/kafka-topics-ui#84] opened 2017-08-30 08:25 UTC
Hi.

I have a topic with some sample data, genereated by the confluent producer with an avro schema. 

But when accessing the topic data from landoop-topics ui i get the "binary" data view. 

![image](https://user-images.githubusercontent.com/1955424/29862625-1c4181fe-8d7e-11e7-8002-2e664731eedc.png)

I should add, that we have a working Kafka setup  with producers and consumers happily serializing and deserializing Confluent Avro messages. But for some reason topics-ui is not able to see these messages as Avro. I am at a loss at where to look. My google-fu is not strong enough.

**Comment by Antwnis** [comment] 2017-08-30 09:26
Hi @dajoni 

1. Does that topic contain Avro on both the KEY and the VALUE of the messages ? Currently Kafka-Rest does not support mixed-content topics i.e. STRING-AVRO for key/value

2. Can you verify that you have registered Avro subjects in the schema-registry ?
If your topic is called `topicA` you should be able to see a `topicA-key` and `topicA-value` schema registered. The kafka-rest deserializers expect to find the matching subjects suffixed with "-key" and "-value"

Also would like to let you know about http://kafka-lenses.io that we recently announced, that is capable of reading mixed-content topics, and provides many additional capabilities

**Comment by dajoni** [comment] 2017-08-30 09:55
Most of our topics are Long / Avro for key/value, so that seems to be our issue. 

I look forward to know more about kafka-lenses.

**Comment by colleen-love** [comment] 2018-04-15 04:27
I'm having the same issue. The topic uses Avro for both KEY and VALUE and those are registered in the schema-registry. However, they Avro schemas use a CustomEncoding for some fields. Is there any way for me to include the CustomEncoding classes in the topic-ui or the kafka-rest-proxy so that I can view the deserialized keys and values?

**Comment by zhonghuiwen** [comment] 2019-03-08 03:50
I had this issue because i had loaded the kafka-topics-ui site before I had added the schema to the schema registry. So the cookie stored by kafka-topics-ui remembered the previous data type being binary. Just had to clear my cookies to get the correct avro deserialized data

**Comment by dwardrian** [comment] 2019-04-27 12:30
@zhonghuiwen I love you.

**Comment by jglambed** [comment] 2019-05-19 20:28
I ll close this ticket as the initial issue reported was eventually the expected behaviour.
@collinscangarella if one year later you are still looking for custom deserializers I would suggest you to pay a visit at www.lenses.io

**Closed as completed by jglambed** 2019-05-19 20:28 UTC
