### ISSUE TITLE
Topic list not loading when ACL denies access to some topics

### ISSUE THREAD

**Issue by BAPostma** [Landoop/kafka-topics-ui#155] opened 2019-12-19 19:55 UTC
I've got the following set-up:
* Client cert in kafka-rest-proxy
  * ACLs (access control lists) are set inside Kafka
  * Access is restricted to only a subset of the topics for the client CN
* kafka-topics-ui loads and requests all topics successfully (visible in chrome debug console)
* certain topics receive a HTTP 403 response for the XHR requests

Expected:
* I see all topics to which access was successful

Actual:
* I see no topics listed in the left-hand-side menu

**Comment by mariosant** [comment] 2019-12-23 09:53
Thanks @BAPostma! I am not 100 percent confident about the expected behavior here, since 403's indicate an issue and thus the operation cannot be marked as successful.
Let me dig around and I will come back at this, shortly.

**Comment by mariosant** [comment] 2019-12-27 13:45
Hey @BAPostma, it seems that we do not support ACL'd setup. However, you can try our [flagship product](https://lenses.io/downloads) which does support that.

**Closed as completed by mariosant** 2019-12-27 13:45 UTC
Labels: wontfix
