### ISSUE TITLE
Topics ui doesn't show topic content 

### ISSUE THREAD

**Issue by maver1ck** [Landoop/kafka-topics-ui#127] opened 2018-08-09 09:12 UTC
Hi,
I tried to use topics ui on k8s.
I build whole deployment and configure topics ui to use kafka-rest via proxy
  KAFKA_REST_PROXY_URL: "http://kafka-rest:8082" # proxy url is dns of service in k8s.
  PROXY: true

I can see list of topics but can't see a content. I tried also to configure CORS for kafka-rest but without success.
Versions:
Kafka-rest: cp-5.0.0
Topics-ui: 0.9.3 (docker image)

Logs:

kafka-topics-ui
```
100.96.5.10 - [09/Aug/2018:09:08:45 +0000] "GET /topics/_schemas HTTP/1.1" 200 953
100.96.5.10 - [09/Aug/2018:09:08:45 +0000] "GET /topics/_schemas/partitions HTTP/1.1" 400 0
```

kafka-rest
```
[2018-08-09 09:08:45,185] INFO 100.96.5.24 - - [09/Aug/2018:09:08:45 +0000] "GET /topics/_schemas HTTP/1.1" 200 953  26 (io.confluent.rest-utils.requests)
[2018-08-09 09:08:45,352] INFO 100.96.5.24 - - [09/Aug/2018:09:08:45 +0000] "GET /topics/_schemas/partitions HTTP/1.1" 400 0  1 (io.confluent.rest-utils.requests)
```

Request / responce from browser:
```
GENERAL:
Request URL: https://K8S_CLUSTER/api/kafka-rest-proxy/topics/_schemas/partitions
Request Method: GET
Status Code: 400 
Remote Address: a.b.c.d:443
Referrer Policy: no-referrer-when-downgrade
```
RESPONSE:
```
cache-control: must-revalidate,no-cache,no-store
content-length: 0
content-type: text/plain; charset=utf-8
date: Thu, 09 Aug 2018 09:11:26 GMT
server: Jetty(9.4.11.v20180605)
status: 400
vary: Accept-Encoding
```
REQUEST:
```
:authority: K8S_CLUSTER
:method: GET
:path: /api/kafka-rest-proxy/topics/_schemas/partitions
:scheme: https
accept: application/vnd.kafka.v2+json, application/vnd.kafka+json, application/json
accept-encoding: gzip, deflate, br
accept-language: pl,en-US;q=0.9,en;q=0.8,und;q=0.7
content-type: 
cookie: _ga=GA1.2.1134432455.1531810287
dnt: 1
referer: https://K8S_ADDRESS/
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36
```

Kafka rest is working... http request from browser to kafka-rest is giving me correct results.
What can be wrong ?

**Comment by sebkim** [comment] 2018-08-10 09:16
i also have this issue.
when curl or postman following url
GET /topics/{topic_name}/partitions,
it works.
However, angular application get just reponse 400 error.

**Comment by raylua2566** [comment] 2018-08-11 01:36
This issue I make a RP #125  to fix it.

The problem is 
REQUEST:
```
...
content-type: 
...
```
Kafka-Rest can not accept a content-type with a empty string value, it will throw a `NullPointerException `  in to server internal, but server do not RESPONSE the actual error reason to frond end.

**Comment by maver1ck** [comment] 2018-08-11 08:14
@raylua2566 great ;)
Waiting for merge and new version :)

**Comment by BaluVyamajala** [comment] 2018-08-13 12:09
I had the same problem! issue is with Confluent Rest Proxy too! those consumer apis doesn't always return events for the first time and topics UI doesn't make an attempt to call the api again.

**Comment by aldgagnon** [comment] 2018-08-14 16:56
Also experiencing this issue. :boom:

**Comment by BaluVyamajala** [comment] 2018-08-14 17:04
Try https://github.com/BaluVyamajala/kafka-ui , this one doesn't use RestProxy, both back end and front end are coded together in this app itself!

**Comment by raylua2566** [comment] 2018-08-15 01:05
I also change the base64 lib to support utf8 encode/decode on my repos forked from Landoop/kafka-topics-ui

**Comment by mrpity** [comment] 2018-08-17 14:22
Hi. The same problem(((.
When it will be merged, anybody knows ?

**Comment by dsebastian** [comment] 2018-08-17 14:47
The PR for this issue was merged. Please check with the latest master.

**Comment by aldgagnon** [comment] 2018-08-17 15:52
When will the docker image be updated?

**Comment by stheppi** [comment] 2018-08-17 15:59
We will do our best to ship it out. Probably end of next week.

**Comment by andmarios** [comment] 2018-08-23 17:16
Hi all. Kafka Topics UI was just bumped to 0.9.4.

You can find it under the `latest` and `0.9.4` tags for `landoop/kafka-topics-ui` docker image.

Thank you for your patience. :)

**Closed as completed** 2018-09-12 08:58 UTC
